# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: combined_manifold.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'combined_manifold.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63ombined_manifold.proto\x12\x07tordial\"+\n\x08Vector3D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"\x80\x01\n\rVectorPayload\x12\x11\n\tvector_id\x18\x01 \x01(\t\x12*\n\x0fvelocity_vector\x18\x02 \x01(\x0b\x32\x11.tordial.Vector3D\x12\x15\n\rthroat_radius\x18\x03 \x01(\x01\x12\x19\n\x11magnetic_coupling\x18\x04 \x01(\x01\"}\n\x11SubstrateResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x13\n\x0bmesh_status\x18\x03 \x01(\t\x12\x19\n\x11processing_stable\x18\x04 \x01(\x08\x12\x17\n\x0f\x65xecution_ticks\x18\x05 \x01(\x03\x32]\n\x12ManifoldController\x12G\n\x11SynchronizeVector\x12\x16.tordial.VectorPayload\x1a\x1a.tordial.SubstrateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'combined_manifold_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTOR3D']._serialized_start=36
  _globals['_VECTOR3D']._serialized_end=79
  _globals['_VECTORPAYLOAD']._serialized_start=82
  _globals['_VECTORPAYLOAD']._serialized_end=210
  _globals['_SUBSTRATERESPONSE']._serialized_start=212
  _globals['_SUBSTRATERESPONSE']._serialized_end=337
  _globals['_MANIFOLDCONTROLLER']._serialized_start=339
  _globals['_MANIFOLDCONTROLLER']._serialized_end=432
# @@protoc_insertion_point(module_scope)
