cat << 'EOF' > grpc_client.py
import sys
import os
import grpc

# Import the autogenerated protocol buffer bindings
import proto.issttoft_pb2 as issttoft_pb2
import proto.issttoft_pb2_grpc as issttoft_pb2_grpc

def run_handshake():
    print("[🔌] Initializing HTTP/2 channel loop to Rust core substrate...")
    
    # Establish connection channel to your running Rust binary socket
    server_address = "127.0.0.1:50051"
    channel = grpc.insecure_channel(server_address)
    
    # Instantiate the client stub mapping
    stub = issttoft_pb2_grpc.InferenceServiceStub(channel)
    
    # Construct the request container payload matching your Rust definitions
    request = issttoft_pb2.HandshakeRequest(
        client_id="Flask_Edge_UI",
        client_type="DASHBOARD_CONTROLLER",
        sovereign_claim="FLAMEKEEPER_EXEC_2026"
    )
    
    try:
        print(f"[🚀] Dispatching HandshakeRequest vector to {server_address}...")
        # Fire synchronous gRPC call
        response = stub.Handshake(request)
        
        # Display the verified responses returning out of the Rust engine
        print("\n==========================================================")
        print(" 🌌 TORDIAL-GS CORE HANDSHAKE CONFIRMED")
        print("==========================================================")
        print(f"  Server Version: {response.server_version}")
        print(f"  Server Time:    {response.server_time}")
        print(f"  Mesh Status:    {response.mesh_status}")
        print(f"  Flamekeeper:    {response.flamekeeper_note}")
        print("==========================================================\n")
        
    except grpc.RpcError as e:
        print(f"❌ gRPC Handshake Failed! Status code: {e.code()} | Details: {e.details()}", file=sys.stderr)

if __name__ == "__main__":
    run_handshake()
EOF
