# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/manifold.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/manifold.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/manifold.proto\x12\x13tordial.manifold.v1\"N\n\x11\x44riftBatchRequest\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\x04\x12\x11\n\tthreshold\x18\x02 \x01(\x01\x12\x14\n\x0cinput_buffer\x18\x03 \x03(\x01\"\xab\x01\n\x12\x44riftBatchResponse\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\x04\x12\x18\n\x10total_iterations\x18\x02 \x01(\x04\x12\x15\n\rbatch_time_ms\x18\x03 \x01(\x01\x12\x13\n\x0bper_pass_ns\x18\x04 \x01(\x01\x12 \n\x18throughput_iters_per_sec\x18\x05 \x01(\x01\x12\x1b\n\x13out_of_bounds_trips\x18\x06 \x01(\x04\x32\x83\x01\n\x18ManifoldInferenceService\x12g\n\x10StreamDriftBatch\x12&.tordial.manifold.v1.DriftBatchRequest\x1a\'.tordial.manifold.v1.DriftBatchResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.manifold_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRIFTBATCHREQUEST']._serialized_start=45
  _globals['_DRIFTBATCHREQUEST']._serialized_end=123
  _globals['_DRIFTBATCHRESPONSE']._serialized_start=126
  _globals['_DRIFTBATCHRESPONSE']._serialized_end=297
  _globals['_MANIFOLDINFERENCESERVICE']._serialized_start=300
  _globals['_MANIFOLDINFERENCESERVICE']._serialized_end=431
# @@protoc_insertion_point(module_scope)
