# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Atmospheric_Vector.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'Atmospheric_Vector.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x41tmospheric_Vector.proto\x12\x0b\x61tmospheric\"\xb8\x01\n\x11\x41tmosphericVector\x12\x0f\n\x07\x63o2_ppm\x18\x01 \x01(\x01\x12\x12\n\no2_percent\x18\x02 \x01(\x01\x12\x18\n\x10humidity_percent\x18\x03 \x01(\x01\x12\x15\n\rtemperature_c\x18\x04 \x01(\x01\x12\x14\n\x0cpressure_hpa\x18\x05 \x01(\x01\x12!\n\x19photosynthetic_efficiency\x18\x06 \x01(\x01\x12\x14\n\x0c\x65ntropy_load\x18\x07 \x01(\x01\"Q\n\tVectorAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x19\n\x11\x62\x61tches_processed\x18\x02 \x01(\x04\x12\x18\n\x10\x61vg_entropy_load\x18\x03 \x01(\x01\x32m\n\x18\x41tmosphericVectorService\x12Q\n\x15StreamAtmosphericData\x12\x1e.atmospheric.AtmosphericVector\x1a\x16.atmospheric.VectorAck(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Atmospheric_Vector_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ATMOSPHERICVECTOR']._serialized_start=42
  _globals['_ATMOSPHERICVECTOR']._serialized_end=226
  _globals['_VECTORACK']._serialized_start=228
  _globals['_VECTORACK']._serialized_end=309
  _globals['_ATMOSPHERICVECTORSERVICE']._serialized_start=311
  _globals['_ATMOSPHERICVECTORSERVICE']._serialized_end=420
# @@protoc_insertion_point(module_scope)
