# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import combined_manifold_pb2 as combined__manifold__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in combined_manifold_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManifoldControllerStub:
    """Multiplexed Core Service Handler
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SynchronizeVector = channel.unary_unary(
                '/tordial.ManifoldController/SynchronizeVector',
                request_serializer=combined__manifold__pb2.VectorPayload.SerializeToString,
                response_deserializer=combined__manifold__pb2.SubstrateResponse.FromString,
                _registered_method=True)


class ManifoldControllerServicer:
    """Multiplexed Core Service Handler
    """

    def SynchronizeVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManifoldControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SynchronizeVector': grpc.unary_unary_rpc_method_handler(
                    servicer.SynchronizeVector,
                    request_deserializer=combined__manifold__pb2.VectorPayload.FromString,
                    response_serializer=combined__manifold__pb2.SubstrateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tordial.ManifoldController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tordial.ManifoldController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManifoldController:
    """Multiplexed Core Service Handler
    """

    @staticmethod
    def SynchronizeVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tordial.ManifoldController/SynchronizeVector',
            combined__manifold__pb2.VectorPayload.SerializeToString,
            combined__manifold__pb2.SubstrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
