[Interface]
Address = 10.51.82.2/31
PrivateKey = rBX4X8nltWXC84QkBUXW5LWnz+gfiPy+Ri/Ssu1JJ2g=
MTU = 1420
Table = 51820

[Peer]
PublicKey = REPLACE_WITH_SERVER_PUBKEY
Endpoint = YOUR_CLOUD_IP:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
