[Interface]
Address = 10.51.82.1/31
ListenPort = 51820
PrivateKey = Yyol/oUVF5QOC0VPoSUGdw5ASjEpoXtdoHIPFAdXnY0=
MTU = 1420
PostUp = sysctl -w net.ipv4.ip_forward=1 && iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE && iptables -A FORWARD -i wg0 -j ACCEPT && iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE && iptables -D FORWARD -i wg0 -j ACCEPT && iptables -t mangle -D FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

[Peer]
PublicKey = REPLACE_WITH_EDGE_PUBKEY
AllowedIPs = 10.51.82.2/32
