# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import issttoft_pb2 as proto_dot_issttoft__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/issttoft_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIntentBand = channel.unary_unary(
                '/issttoft.InferenceService/GetIntentBand',
                request_serializer=proto_dot_issttoft__pb2.GetIntentBandRequest.SerializeToString,
                response_deserializer=proto_dot_issttoft__pb2.IntentBand.FromString,
                _registered_method=True)
        self.GetAllIntentBands = channel.unary_unary(
                '/issttoft.InferenceService/GetAllIntentBands',
                request_serializer=proto_dot_issttoft__pb2.GetAllIntentBandsRequest.SerializeToString,
                response_deserializer=proto_dot_issttoft__pb2.GetAllIntentBandsResponse.FromString,
                _registered_method=True)
        self.StreamIntentUpdates = channel.unary_stream(
                '/issttoft.InferenceService/StreamIntentUpdates',
                request_serializer=proto_dot_issttoft__pb2.StreamIntentUpdatesRequest.SerializeToString,
                response_deserializer=proto_dot_issttoft__pb2.IntentUpdate.FromString,
                _registered_method=True)
        self.Handshake = channel.unary_unary(
                '/issttoft.InferenceService/Handshake',
                request_serializer=proto_dot_issttoft__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=proto_dot_issttoft__pb2.HandshakeResponse.FromString,
                _registered_method=True)


class InferenceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetIntentBand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllIntentBands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamIntentUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Handshake(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIntentBand': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntentBand,
                    request_deserializer=proto_dot_issttoft__pb2.GetIntentBandRequest.FromString,
                    response_serializer=proto_dot_issttoft__pb2.IntentBand.SerializeToString,
            ),
            'GetAllIntentBands': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllIntentBands,
                    request_deserializer=proto_dot_issttoft__pb2.GetAllIntentBandsRequest.FromString,
                    response_serializer=proto_dot_issttoft__pb2.GetAllIntentBandsResponse.SerializeToString,
            ),
            'StreamIntentUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamIntentUpdates,
                    request_deserializer=proto_dot_issttoft__pb2.StreamIntentUpdatesRequest.FromString,
                    response_serializer=proto_dot_issttoft__pb2.IntentUpdate.SerializeToString,
            ),
            'Handshake': grpc.unary_unary_rpc_method_handler(
                    servicer.Handshake,
                    request_deserializer=proto_dot_issttoft__pb2.HandshakeRequest.FromString,
                    response_serializer=proto_dot_issttoft__pb2.HandshakeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'issttoft.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('issttoft.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetIntentBand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/issttoft.InferenceService/GetIntentBand',
            proto_dot_issttoft__pb2.GetIntentBandRequest.SerializeToString,
            proto_dot_issttoft__pb2.IntentBand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllIntentBands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/issttoft.InferenceService/GetAllIntentBands',
            proto_dot_issttoft__pb2.GetAllIntentBandsRequest.SerializeToString,
            proto_dot_issttoft__pb2.GetAllIntentBandsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamIntentUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/issttoft.InferenceService/StreamIntentUpdates',
            proto_dot_issttoft__pb2.StreamIntentUpdatesRequest.SerializeToString,
            proto_dot_issttoft__pb2.IntentUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Handshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/issttoft.InferenceService/Handshake',
            proto_dot_issttoft__pb2.HandshakeRequest.SerializeToString,
            proto_dot_issttoft__pb2.HandshakeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
