# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/issttoft.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'proto/issttoft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/issttoft.proto\x12\x08issttoft\"\'\n\x14GetIntentBandRequest\x12\x0f\n\x07\x62\x61nd_id\x18\x01 \x01(\t\"\x1a\n\x18GetAllIntentBandsRequest\"@\n\x19GetAllIntentBandsResponse\x12#\n\x05\x62\x61nds\x18\x01 \x03(\x0b\x32\x14.issttoft.IntentBand\"/\n\nIntentBand\x12\x0f\n\x07\x62\x61nd_id\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\"/\n\x1aStreamIntentUpdatesRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\"E\n\x0cIntentUpdate\x12\x0f\n\x07\x62\x61nd_id\x18\x01 \x01(\t\x12\x14\n\x0cintent_value\x18\x02 \x01(\x01\x12\x0e\n\x06reason\x18\x03 \x01(\t\"S\n\x10HandshakeRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63lient_type\x18\x02 \x01(\t\x12\x17\n\x0fsovereign_claim\x18\x03 \x01(\t\"\x9c\x01\n\x11HandshakeResponse\x12+\n\rinitial_bands\x18\x01 \x03(\x0b\x32\x14.issttoft.IntentBand\x12\x16\n\x0eserver_version\x18\x02 \x01(\t\x12\x13\n\x0bserver_time\x18\x03 \x01(\x03\x12\x13\n\x0bmesh_status\x18\x04 \x01(\t\x12\x18\n\x10\x66lamekeeper_note\x18\x05 \x01(\t2\xd4\x02\n\x10InferenceService\x12\x45\n\rGetIntentBand\x12\x1e.issttoft.GetIntentBandRequest\x1a\x14.issttoft.IntentBand\x12\\\n\x11GetAllIntentBands\x12\".issttoft.GetAllIntentBandsRequest\x1a#.issttoft.GetAllIntentBandsResponse\x12U\n\x13StreamIntentUpdates\x12$.issttoft.StreamIntentUpdatesRequest\x1a\x16.issttoft.IntentUpdate0\x01\x12\x44\n\tHandshake\x12\x1a.issttoft.HandshakeRequest\x1a\x1b.issttoft.HandshakeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.issttoft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETINTENTBANDREQUEST']._serialized_start=34
  _globals['_GETINTENTBANDREQUEST']._serialized_end=73
  _globals['_GETALLINTENTBANDSREQUEST']._serialized_start=75
  _globals['_GETALLINTENTBANDSREQUEST']._serialized_end=101
  _globals['_GETALLINTENTBANDSRESPONSE']._serialized_start=103
  _globals['_GETALLINTENTBANDSRESPONSE']._serialized_end=167
  _globals['_INTENTBAND']._serialized_start=169
  _globals['_INTENTBAND']._serialized_end=216
  _globals['_STREAMINTENTUPDATESREQUEST']._serialized_start=218
  _globals['_STREAMINTENTUPDATESREQUEST']._serialized_end=265
  _globals['_INTENTUPDATE']._serialized_start=267
  _globals['_INTENTUPDATE']._serialized_end=336
  _globals['_HANDSHAKEREQUEST']._serialized_start=338
  _globals['_HANDSHAKEREQUEST']._serialized_end=421
  _globals['_HANDSHAKERESPONSE']._serialized_start=424
  _globals['_HANDSHAKERESPONSE']._serialized_end=580
  _globals['_INFERENCESERVICE']._serialized_start=583
  _globals['_INFERENCESERVICE']._serialized_end=923
# @@protoc_insertion_point(module_scope)
