cat > src/main.rs << 'EOF'
//! Tordial-GS Manifold — Sovereign Inference Service (gRPC Entry Point)
//! Prepared for future integration with Python IntentPlanner (via JSON or PyO3)

use std::net::SocketAddr;
use tonic::{transport::Server, Request, Response, Status};
use tracing::info;

pub mod issttoft {
    tonic::include_proto!("issttoft");
}

// TODO: Create src/intent_engine.rs with IntentEngine, BasinValidator, etc.
// For now this is a stub so the project compiles.
mod intent_engine;
use intent_engine::{IntentEngine, BasinValidator};

use issttoft::{
    inference_service_server::{InferenceService, InferenceServiceServer},
    GetAllIntentBandsRequest, GetAllIntentBandsResponse,
    GetIntentBandRequest, IntentBand,
    GlyphRequest, GlyphResponse,
    PulseRequest, PulseResponse,
    HandshakeRequest, HandshakeResponse,
    StreamIntentUpdatesRequest,
};

#[derive(Clone)]
pub struct SovereignInferenceService {
    engine: IntentEngine,
}

impl SovereignInferenceService {
    pub fn new() -> Self {
        Self { engine: IntentEngine::new() }
    }
}

#[tonic::async_trait]
impl InferenceService for SovereignInferenceService {
    async fn get_intent_band(
        &self,
        request: Request<GetIntentBandRequest>,
    ) -> Result<Response<IntentBand>, Status> {
        let req = request.into_inner();
        if let Some(band) = self.engine.get_all_bands().into_iter().find(|b| b.band_id == req.band_id) {
            Ok(Response::new(band))
        } else {
            Err(Status::not_found(format!("Band not found: {}", req.band_id)))
        }
    }

    async fn get_all_intent_bands(
        &self,
        _request: Request<GetAllIntentBandsRequest>,
    ) -> Result<Response<GetAllIntentBandsResponse>, Status> {
        Ok(Response::new(GetAllIntentBandsResponse { bands: self.engine.get_all_bands() }))
    }

    async fn encode_rad_hard_glyph(
        &self,
        _request: Request<GlyphRequest>,
    ) -> Result<Response<GlyphResponse>, Status> {
        // TODO: Integrate output from Python intent/intent_planner.py here
        Err(Status::unimplemented("Not implemented yet"))
    }

    async fn run_clientless_pulse(
        &self,
        _request: Request<PulseRequest>,
    ) -> Result<Response<PulseResponse>, Status> {
        Err(Status::unimplemented("Not implemented yet"))
    }

    type StreamIntentUpdatesStream = tonic::codegen::tokio_stream::wrappers::ReceiverStream<
        Result<issttoft::IntentUpdate, Status>
    >;

    async fn stream_intent_updates(
        &self,
        _request: Request<StreamIntentUpdatesRequest>,
    ) -> Result<Response<Self::StreamIntentUpdatesStream>, Status> {
        Err(Status::unimplemented("Streaming not wired yet"))
    }

    async fn handshake(
        &self,
        request: Request<HandshakeRequest>,
    ) -> Result<Response<HandshakeResponse>, Status> {
        let req = request.into_inner();
        let resp = self.engine.handshake(req.client_id, req.client_type, req.sovereign_claim);
        Ok(Response::new(resp))
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    tracing_subscriber::fmt::init();

    info!("🔥 Tordial-GS Manifold starting...");

    // === Engine Initialization ===
    let service = SovereignInferenceService::new();

    // Demo basin / regime classification
    let dist = BasinValidator::distance_to_ridge(27.0, 155.0, 60.0, 0.325);
    let regime = BasinValidator::classify_regime(27.0, 155.0, 60.0, 0.325);
    info!("Basin distance = {:.2}, regime = {:?}", dist, regime);

    // === Python IntentPlanner Integration Point ===
    // TODO: Load plans generated by Python `intent/intent_planner.py` (JSON)
    // Future: Direct call via PyO3 or read plan JSON and feed into GS feedback laws

    let addr: SocketAddr = "0.0.0.0:50051".parse()?;
    info!("Tordial-GS Manifold gRPC server listening on {}", addr);

    Server::builder()
        .add_service(InferenceServiceServer::new(service))
        .serve(addr)
        .await?;

    Ok(())
}
EOF