use tonic::{transport::Server, Request, Response, Status};
use std::net::SocketAddr;

// Import the code generated by tonic-build from our proto definition
pub mod tordial {
    tonic::include_proto!("tordial");
}

use tordial::inference_service_server::{InferenceService, InferenceServiceServer};
use tordial::{VectorPayload, SubstrateResponse};

#[derive(Debug, Default)]
pub struct SovereignManifoldSubstrate {}

#[tonic::async_trait]
impl InferenceService for SovereignManifoldSubstrate {
    async fn process_vector(
        &self,
        request: Request<VectorPayload>,
    ) -> Result<Response<SubstrateResponse>, Status> {
        let payload = request.into_inner();
        
        println!("📥 [SUBSTRATE CORE] Ingested Biophysical Vector: {}", payload.vector_id);
        if let Some(matrix) = payload.economic_vector {
            println!("   ⚡ Flux Velocity (F_m): {} nT", matrix.capital_velocity);
            println!("   ⚡ Env Friction (E_f) : {}", matrix.regulatory_drag);
            println!("   ⚡ Mass Expansion(M_o): {}", matrix.yield_generation);
        }

        // Return the invariant sovereign balance response
        let reply = SubstrateResponse {
            status: "PROCESSED".to_string(),
            version: "1.0.0-ALGEBRA".to_string(),
            arbitrage_status: "SOVEREIGN_LOCK_SUSTAINED".to_string(),
            execution_stable: true,
            tracking_ticks: 1,
        };

        Ok(Response::new(reply))
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let addr: SocketAddr = "127.0.0.1:50055".parse()?;
    let service = SovereignManifoldSubstrate::default();

    println!("══════════════════════════════════════════════════════════════");
    println!("🚀 [ECONOMIC SUBSTRATE] Sovereign Loop Matrix Active: {}", addr);
    println!("════════════════════════════════════════════ll════════════════");

    Server::builder()
        .add_service(InferenceServiceServer::new(service))
        .serve(addr)
        .await?;

    Ok(())
}
